services:
  - type: web
    name: chat-app
    env: node
    buildCommand: cd client && npm install && npm run build && cd .. && npm install
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production 